apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: web
    tier: app
  clusterIP: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-app
imagePullSecrets:
- name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
      tier: app
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        tier: app
    spec:
      serviceAccountName: web-app
      containers:
      - image: gcr.io/savvy-concord-255819/web:latest
        name: web
        ports:
        - containerPort: 80
          name: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: ajaffie.cse356.compas.cs.stonybrook.edu
    http:
      paths:
      - path: /app/(.*)
        backend:
          serviceName: web
          servicePort: http
  - host: dootr.ajaffie.dev
    http:
      paths:
      - path: /app/(.*)
        backend:
          serviceName: web
          servicePort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-redirect
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: /app
spec:
  rules:
  - host: ajaffie.cse356.compas.cs.stonybrook.edu
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: http
  - host: dootr.ajaffie.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: web
          servicePort: http
