apiVersion: v1
kind: Service
metadata:
  name: mailer
  labels:
    app: auth
spec:
  ports:
  - port: 25
  selector:
    app: auth
    tier: mailer
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
      tier: mailer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth
        tier: mailer
    spec:
      initContainers:
      - name: mailer-fix-permissions
        image: busybox
        command:
        - /bin/sh
        - -c
        - "mkdir -p /etc/opendkim/domainkeys && cp /tmp/domainkeys/.private /etc/opendkim/domainkeys && chown -R 103:108 /etc/opendkim/domainkeys && chmod -R 440 /etc/opendkim/domainkeys"
        volumeMounts:
        - name: mailer-dkim
          mountPath: /tmp/domainkeys
          readOnly: true
        securityContext:
          runAsUser: 0
      containers:
      - image: catatnight/postfix:latest
        name: mailer
        env:
        - name: maildomain
          value: dootr.ajaffie.dev
        - name: smtp_user
          valueFrom:
            secretKeyRef:
              name: mailer-creds
              key: creds
        ports:
        - containerPort: 25
          name: smtp
      volumes:
      - name: mailer-dkim
        secret:
          secretName: mailer-dkim-secret
          items:
          - key: mail.private
            path: .private
        