apiVersion: v1
kind: Service
metadata:
  name: dootdb
  labels:
    app: doots
spec:
  ports:
  - port: 3306
  selector:
    app: doots
    tier: dootdb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dootdb-data
  labels:
    app: doots
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dootdb
  labels:
    app: doots
spec:
  selector:
    matchLabels:
      app: doots
      tier: dootdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: doots
        tier: dootdb
    spec:
      initContainers:
        - name: volume-permissions
          image: bitnami/minideb:stretch
          imagePullPolicy: IfNotPresent
          command: ["chown", "-R", "1001:1001", "/bitnami/mariadb"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: dootdb-persistent-storage
              mountPath: /bitnami/mariadb
      containers:
      - image: bitnami/mariadb:10.3
        name: dootdb
        env:
        - name: MARIADB_DATABASE
          value: dootr.doots
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dootdb-creds
              key: root
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: dootdb-creds
              key: username
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dootdb-creds
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: dootdb-persistent-storage
          mountPath: /bitnami/mariadb
      volumes:
      - name: dootdb-persistent-storage
        persistentVolumeClaim:
          claimName: dootdb-data