apiVersion: v1
kind: Service
metadata:
  name: doots
  labels:
    app: doots
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: doots
    tier: app
  clusterIP: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: doots-app
imagePullSecrets:
- name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doots
  labels:
    app: doots
spec:
  selector:
    matchLabels:
      app: doots
      tier: app
  strategy:
    type: Recreate
  replicas: 3
  template:
    metadata:
      labels:
        app: doots
        tier: app
    spec:
      serviceAccountName: doots-app
      containers:
      - image: gcr.io/savvy-concord-255819/doots:latest
        name: doots
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: QUARKUS_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: dootdb-creds
              key: username
        - name: QUARKUS_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dootdb-creds
              key: password
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: doots
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /additem
        backend:
          serviceName: doots
          servicePort: http
      - path: /item/[0-9]*
        backend:
          serviceName: doots
          servicePort: http
      - path: /search
        backend:
          serviceName: doots
          servicePort: http